// Generated by scripts/generate-renderer-resource-map.mjs -- do not edit by hand.
import berserk from '@screeps/renderer-metadata/images/berserk.svg?url'
import bodyPartBar from '@screeps/renderer-metadata/images/bodyPartBar.svg?url'
import commanderLvl0 from '@screeps/renderer-metadata/images/commander-lvl0.svg?url'
import commanderLvl1 from '@screeps/renderer-metadata/images/commander-lvl1.svg?url'
import commanderLvl2 from '@screeps/renderer-metadata/images/commander-lvl2.svg?url'
import commanderLvl3 from '@screeps/renderer-metadata/images/commander-lvl3.svg?url'
import commanderLvl4 from '@screeps/renderer-metadata/images/commander-lvl4.svg?url'
import constructedWall from '@screeps/renderer-metadata/images/constructedWall.svg?url'
import controller from '@screeps/renderer-metadata/images/controller.svg?url'
import controllerLevel from '@screeps/renderer-metadata/images/controller-level.svg?url'
import disruptSource from '@screeps/renderer-metadata/images/disrupt-source.svg?url'
import cover from '@screeps/renderer-metadata/images/cover.svg?url'
import creepNpc from '@screeps/renderer-metadata/images/creep-npc.svg?url'
import creepMask from '@screeps/renderer-metadata/images/creep-mask.png?url'
import defend from '@screeps/renderer-metadata/images/defend.svg?url'
import demolish from '@screeps/renderer-metadata/images/demolish.svg?url'
import depositBiomass from '@screeps/renderer-metadata/images/deposit-biomass.svg?url'
import depositBiomassFill from '@screeps/renderer-metadata/images/deposit-biomass-fill.svg?url'
import depositMetal from '@screeps/renderer-metadata/images/deposit-metal.svg?url'
import depositMetalFill from '@screeps/renderer-metadata/images/deposit-metal-fill.svg?url'
import depositMist from '@screeps/renderer-metadata/images/deposit-mist.svg?url'
import depositMistFill from '@screeps/renderer-metadata/images/deposit-mist-fill.svg?url'
import depositSilicon from '@screeps/renderer-metadata/images/deposit-silicon.svg?url'
import depositSiliconFill from '@screeps/renderer-metadata/images/deposit-silicon-fill.svg?url'
import disable from '@screeps/renderer-metadata/images/disable.svg?url'
import disruptSpawn from '@screeps/renderer-metadata/images/disrupt-spawn.svg?url'
import disruptTower from '@screeps/renderer-metadata/images/disrupt-tower.svg?url'
import disruptTerminal from '@screeps/renderer-metadata/images/disrupt-terminal.svg?url'
import drainExtension from '@screeps/renderer-metadata/images/drain-extension.svg?url'
import encourage from '@screeps/renderer-metadata/images/encourage.svg?url'
import exhaust from '@screeps/renderer-metadata/images/exhaust.svg?url'
import regenerateMineral from '@screeps/renderer-metadata/images/regen-mineral.svg?url'
import regenerateSource from '@screeps/renderer-metadata/images/regen-source.svg?url'
import factory from '@screeps/renderer-metadata/images/factory.svg?url'
import factoryLvl0 from '@screeps/renderer-metadata/images/factory-lvl0.svg?url'
import factoryLvl1 from '@screeps/renderer-metadata/images/factory-lvl1.svg?url'
import factoryLvl2 from '@screeps/renderer-metadata/images/factory-lvl2.svg?url'
import factoryLvl3 from '@screeps/renderer-metadata/images/factory-lvl3.svg?url'
import factoryLvl4 from '@screeps/renderer-metadata/images/factory-lvl4.svg?url'
import factoryLvl5 from '@screeps/renderer-metadata/images/factory-lvl5.svg?url'
import factoryBorder from '@screeps/renderer-metadata/images/factory-border.svg?url'
import factoryHighlight from '@screeps/renderer-metadata/images/factory-highlight.svg?url'
import flag from '@screeps/renderer-metadata/images/flag.svg?url'
import flagSecondary from '@screeps/renderer-metadata/images/flag-secondary.svg?url'
import executorLvl0 from '@screeps/renderer-metadata/images/executor-lvl0.svg?url'
import executorLvl1 from '@screeps/renderer-metadata/images/executor-lvl1.svg?url'
import executorLvl2 from '@screeps/renderer-metadata/images/executor-lvl2.svg?url'
import executorLvl3 from '@screeps/renderer-metadata/images/executor-lvl3.svg?url'
import executorLvl4 from '@screeps/renderer-metadata/images/executor-lvl4.svg?url'
import extension from '@screeps/renderer-metadata/images/extension.svg?url'
import extensionBorder50 from '@screeps/renderer-metadata/images/extension-border50.svg?url'
import extensionBorder100 from '@screeps/renderer-metadata/images/extension-border100.svg?url'
import extensionBorder200 from '@screeps/renderer-metadata/images/extension-border200.svg?url'
import extractor from '@screeps/renderer-metadata/images/extractor.svg?url'
import exitLeft from '@screeps/renderer-metadata/images/exit-left.svg?url'
import exitTop from '@screeps/renderer-metadata/images/exit-top.svg?url'
import exitBottom from '@screeps/renderer-metadata/images/exit-bottom.svg?url'
import exitRight from '@screeps/renderer-metadata/images/exit-right.svg?url'
import flare1 from '@screeps/renderer-metadata/images/flare1.png?url'
import flare2 from '@screeps/renderer-metadata/images/flare2.png?url'
import flare3 from '@screeps/renderer-metadata/images/flare3.png?url'
import harvestEnergy from '@screeps/renderer-metadata/images/harvest-energy.svg?url'
import harvestMineral from '@screeps/renderer-metadata/images/harvest-mineral.svg?url'
import generateOps from '@screeps/renderer-metadata/images/generate-ops.svg?url'
import glow from '@screeps/renderer-metadata/images/glow.png?url'
import ground from '@screeps/renderer-metadata/images/ground.png?url'
import groundMask from '@screeps/renderer-metadata/images/ground-mask.png?url'
import kill from '@screeps/renderer-metadata/images/kill.svg?url'
import lab from '@screeps/renderer-metadata/images/lab.svg?url'
import labHighlight from '@screeps/renderer-metadata/images/lab-highlight.svg?url'
import labMineral from '@screeps/renderer-metadata/images/lab-mineral.svg?url'
import link from '@screeps/renderer-metadata/images/link.svg?url'
import linkEnergy from '@screeps/renderer-metadata/images/link-energy.svg?url'
import linkBorder from '@screeps/renderer-metadata/images/link-border.svg?url'
import massRepair from '@screeps/renderer-metadata/images/mass-repair.svg?url'
import noise1 from '@screeps/renderer-metadata/images/noise1.png?url'
import noise2 from '@screeps/renderer-metadata/images/noise2.png?url'
import nuke from '@screeps/renderer-metadata/images/nuke.svg?url'
import nuker from '@screeps/renderer-metadata/images/nuker.svg?url'
import nukerBorder from '@screeps/renderer-metadata/images/nuker-border.svg?url'
import operateExtension from '@screeps/renderer-metadata/images/operate-extension.svg?url'
import operateLab from '@screeps/renderer-metadata/images/operate-lab.svg?url'
import operateObserver from '@screeps/renderer-metadata/images/operate-observer.svg?url'
import operateSpawn from '@screeps/renderer-metadata/images/operate-spawn.svg?url'
import operateStorage from '@screeps/renderer-metadata/images/operate-storage.svg?url'
import operateTerminal from '@screeps/renderer-metadata/images/operate-terminal.svg?url'
import operateTower from '@screeps/renderer-metadata/images/operate-tower.svg?url'
import operatorLvl0 from '@screeps/renderer-metadata/images/operator-lvl0.svg?url'
import operatorLvl1 from '@screeps/renderer-metadata/images/operator-lvl1.svg?url'
import operatorLvl2 from '@screeps/renderer-metadata/images/operator-lvl2.svg?url'
import operatorLvl3 from '@screeps/renderer-metadata/images/operator-lvl3.svg?url'
import operatorLvl4 from '@screeps/renderer-metadata/images/operator-lvl4.svg?url'
import powerBank from '@screeps/renderer-metadata/images/powerBank.svg?url'
import punch from '@screeps/renderer-metadata/images/punch.svg?url'
import rampart from '@screeps/renderer-metadata/images/rampart.svg?url'
import rectangle from '@screeps/renderer-metadata/images/rectangle.svg?url'
import reflect from '@screeps/renderer-metadata/images/reflect.svg?url'
import reinforce from '@screeps/renderer-metadata/images/reinforce.svg?url'
import remoteTransfer from '@screeps/renderer-metadata/images/remote-transfer.svg?url'
import renew from '@screeps/renderer-metadata/images/renew.svg?url'
import shield from '@screeps/renderer-metadata/images/shield.svg?url'
import sight from '@screeps/renderer-metadata/images/sight.svg?url'
import snipe from '@screeps/renderer-metadata/images/snipe.svg?url'
import storage from '@screeps/renderer-metadata/images/storage.svg?url'
import storageBorder from '@screeps/renderer-metadata/images/storage-border.svg?url'
import summon from '@screeps/renderer-metadata/images/summon.svg?url'
import tbd from '@screeps/renderer-metadata/images/tbd.svg?url'
import terminal from '@screeps/renderer-metadata/images/terminal.svg?url'
import terminalBorder from '@screeps/renderer-metadata/images/terminal-border.svg?url'
import terminalHighlight from '@screeps/renderer-metadata/images/terminal-highlight.svg?url'
import terminalArrows from '@screeps/renderer-metadata/images/terminal-arrows.svg?url'
import tombstoneBorder from '@screeps/renderer-metadata/images/tombstone-border.svg?url'
import tombstoneResource from '@screeps/renderer-metadata/images/tombstone-resource.svg?url'
import tough from '@screeps/renderer-metadata/images/tough.svg?url'
import towerBase from '@screeps/renderer-metadata/images/tower-base.svg?url'
import towerRotatable from '@screeps/renderer-metadata/images/tower-rotatable.svg?url'
import towerRotatableNpc from '@screeps/renderer-metadata/images/tower-rotatable-npc.svg?url'
import invaderCore from '@screeps/renderer-metadata/images/invaderCore.svg?url'
import ruin from '@screeps/renderer-metadata/images/ruin.svg?url'

export const resourceMap: Record<string, string> = {
  berserk,
  bodyPartBar,
  'commander-lvl0': commanderLvl0,
  'commander-lvl1': commanderLvl1,
  'commander-lvl2': commanderLvl2,
  'commander-lvl3': commanderLvl3,
  'commander-lvl4': commanderLvl4,
  constructedWall,
  controller,
  'controller-level': controllerLevel,
  'disrupt-source': disruptSource,
  cover,
  'creep-npc': creepNpc,
  'creep-mask': creepMask,
  defend,
  demolish,
  'deposit-biomass': depositBiomass,
  'deposit-biomass-fill': depositBiomassFill,
  'deposit-metal': depositMetal,
  'deposit-metal-fill': depositMetalFill,
  'deposit-mist': depositMist,
  'deposit-mist-fill': depositMistFill,
  'deposit-silicon': depositSilicon,
  'deposit-silicon-fill': depositSiliconFill,
  disable,
  'disrupt-spawn': disruptSpawn,
  'disrupt-tower': disruptTower,
  'disrupt-terminal': disruptTerminal,
  'drain-extension': drainExtension,
  encourage,
  exhaust,
  'regenerate-mineral': regenerateMineral,
  'regenerate-source': regenerateSource,
  factory,
  'factory-lvl0': factoryLvl0,
  'factory-lvl1': factoryLvl1,
  'factory-lvl2': factoryLvl2,
  'factory-lvl3': factoryLvl3,
  'factory-lvl4': factoryLvl4,
  'factory-lvl5': factoryLvl5,
  'factory-border': factoryBorder,
  'factory-highlight': factoryHighlight,
  flag,
  'flag-secondary': flagSecondary,
  'executor-lvl0': executorLvl0,
  'executor-lvl1': executorLvl1,
  'executor-lvl2': executorLvl2,
  'executor-lvl3': executorLvl3,
  'executor-lvl4': executorLvl4,
  extension,
  'extension-border50': extensionBorder50,
  'extension-border100': extensionBorder100,
  'extension-border200': extensionBorder200,
  extractor,
  'exit-left': exitLeft,
  'exit-top': exitTop,
  'exit-bottom': exitBottom,
  'exit-right': exitRight,
  flare1,
  flare2,
  flare3,
  'harvest-energy': harvestEnergy,
  'harvest-mineral': harvestMineral,
  'generate-ops': generateOps,
  glow,
  ground,
  'ground-mask': groundMask,
  kill,
  lab,
  'lab-highlight': labHighlight,
  'lab-mineral': labMineral,
  link,
  'link-energy': linkEnergy,
  'link-border': linkBorder,
  'mass-repair': massRepair,
  noise1,
  noise2,
  nuke,
  nuker,
  'nuker-border': nukerBorder,
  'operate-extension': operateExtension,
  'operate-lab': operateLab,
  'operate-observer': operateObserver,
  'operate-spawn': operateSpawn,
  'operate-storage': operateStorage,
  'operate-terminal': operateTerminal,
  'operate-tower': operateTower,
  'operator-lvl0': operatorLvl0,
  'operator-lvl1': operatorLvl1,
  'operator-lvl2': operatorLvl2,
  'operator-lvl3': operatorLvl3,
  'operator-lvl4': operatorLvl4,
  powerBank,
  punch,
  rampart,
  rectangle,
  reflect,
  reinforce,
  'remote-transfer': remoteTransfer,
  renew,
  shield,
  sight,
  snipe,
  storage,
  'storage-border': storageBorder,
  summon,
  tbd,
  terminal,
  'terminal-border': terminalBorder,
  'terminal-highlight': terminalHighlight,
  'terminal-arrows': terminalArrows,
  'tombstone-border': tombstoneBorder,
  'tombstone-resource': tombstoneResource,
  tough,
  'tower-base': towerBase,
  'tower-rotatable': towerRotatable,
  'tower-rotatable-npc': towerRotatableNpc,
  invaderCore,
  ruin,
}
